import type { Metadata } from 'next';
import { Anonymous_Pro, Geist, Vazirmatn } from 'next/font/google';
import './globals.css';
import AppProvider from '@/app/app-provider';

const geist = Geist({
	subsets: ['latin'],
	variable: '--font-geist',
});

const vazirmatn = Vazirmatn({
	subsets: ['arabic', 'latin'],
	variable: '--font-vazirmatn',
});

const anonymousPro = Anonymous_Pro({
	subsets: ['latin'],
	weight: ['400', '700'],
	variable: '--font-anonymous-pro',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" dir="ltr" className={`${geist.variable} ${vazirmatn.variable} ${anonymousPro.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col">
				<AppProvider>{children}</AppProvider>
			</body>
		</html>
	);
}
